### ISSUE TITLE
Focus indicator is not clearly visible on "Terms" link on the map

### ISSUE THREAD

**Issue by vedikans** [Microsoft/BingMapsV8CodeSamples#30] opened 2020-10-20 21:40 UTC
As shown in the picture below, the focus indicator does not completely surround the Terms link.
Additional padding-top ,padding-bottom and padding-right is required on the 'TermsLinkContainer' id in the html.

![image](https://user-images.githubusercontent.com/73200563/96646933-bd6e5c00-12e1-11eb-9c7d-c6f6c3eae724.png)

**Comment by IoTGirl** [comment] 2021-01-13 01:27
Hi @vedikans,
I have given your feedback to the V8 control team but the current behavior is "By Design" so I will close this request.
Sincerely,
IoTGirl

**Closed as completed by IoTGirl** 2021-01-13 01:27 UTC
